version: '2'
services:
  web:
    build:
      context: ./
      dockerfile: deploy/web.docker
    extra_hosts:
      - "host.docker.internal:172.20.0.1"
    volumes:
      - ./:/var/www
    ports:
      - "8080:80"
    links:
      - app
  app:
    depends_on:
      - database
    build:
      context: ./
      dockerfile: deploy/app.docker
    extra_hosts:
      - "host.docker.internal:172.20.0.1"
    volumes:
      - ./:/var/www
    links:
      - database
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"
  database:
    image: mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=myrootpass"
      - "MYSQL_DATABASE=rssfeeds"
    ports:
      - "3306:3306"
    volumes:
      - mysqltest:/var/lib/mysql
      - ./logs:/var/log/mysql
      - ./conf.d:/etc/mysql/conf.d

  composer:
    image: composer
    working_dir: /var/www
    volumes:
      - ./:/var/www
    command: update

volumes:
  mysqltest:
    driver: "local"
